package cn.yqius.projects.dao;

import cn.yqius.projects.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jul 31 23:52:46 CST 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jul 31 23:52:46 CST 2019
     */
    int insertSelective(UserPasswordDO record);
}