package cn.yqius.projects.dao;

import cn.yqius.projects.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jul 31 23:52:46 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jul 31 23:52:46 CST 2019
     */
    int insertSelective(UserDO record);
}